# Use the official MongoDB image as the base image
FROM mongo:6.0.4

# Set environment variables for MongoDB initialization
ENV MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER:-mongodb}
ENV MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-mongodb}
ENV MONGO_INITDB_DATABASE=admin
ENV MONGO_AIVERIFY_PASSWORD=${DB_AIVERIFY_PASSWORD:-aiverify}

# Copy MongoDB initialization scripts into the container
COPY ./mongo-init/mongo-init.sh /docker-entrypoint-initdb.d/mongo-init.sh