# Use the official Redis image as the base image
FROM redis:6.2-alpine

# Copy your custom Redis configuration file into the container
COPY ./redis-init/redis.conf /etc/redis/redis.conf

# Start Redis with the custom configuration
CMD ["redis-server", "--save", "20", "1", "--loglevel", "warning", "--include", "/etc/redis/redis.conf"]